callbacks:
  image_logger:
    params:
      visualize_step: 100
    target: callbacks.image_logger.ImageLogger
flush_log_secs: 120
log_every_n_steps: 10
logdir: ./logs
runner:
  params:
    color_lr: 0.005
    criteria_config:
      knn_reg:
        params:
          weight: 0.01
        target: criteria.gaussians_reg.KNNReg
      l2_loss:
        params:
          weight: 1.0
        target: criteria.l2_loss.L2Loss
      opacity_reg:
        params:
          weight: 0.001
        target: criteria.gaussians_reg.OpacityReg
      perceptual_loss:
        params:
          weight: 0.01
        target: criteria.perceptual_loss.PerceptualLoss
      segmentation_loss:
        params:
          weight: 0.1
        target: criteria.dice_loss.DiceLoss
      sobel_loss:
        params:
          weight: 1.0
        target: criteria.sobel_loss.SobelLoss
      ssim_loss:
        params:
          weight: 0.1
        target: criteria.ssim_loss.SSIMLoss
      tv_loss:
        params:
          weight: 0.01
        target: criteria.tv_loss.TVLoss
    densify_start: 100
    densify_step: 201
    densify_stop: 2500
    final_position_lr: 1.6e-06
    gaussians_optimize_steps: 3000
    gender: male
    lr_texture: 0.01
    max_s_value: 0.1
    min_s_value: 0.0
    opacity_lr: 0.05
    opacity_optimize_steps: 5000
    pose_lr: 0.0002
    position_lr: 0.00016
    prune_start: 0
    prune_step: 201
    prune_stop: 100000
    render_size: 1080
    rotation_lr: 0.005
    scaling_lr: 0.005
    smplx_path: /mounted/home/dresden/repositories/HAHA/data
    texture_optimize_steps: 2500
    texture_size: 512
    use_pca_for_hands: false
  target: runners.train_gaussians.TextureAndGaussianTrainer
train_dataloader:
  batch_size: 4
  num_workers: 4
  params:
    data_root: /mounted/home/dresden/repositories/debug/GSAC/Data/v0302/train/
    random_background: true
    render_size: 1080
    use_hashing: false
  target: dataloaders.custom_loader.DataLoader
val_check_interval: 1.0
val_dataloader:
  batch_size: 4
  num_workers: 4
  params:
    data_root: /mounted/home/dresden/repositories/debug/GSAC/Data/v0302/train/
    render_size: 1080
  target: dataloaders.custom_loader.DataLoader
